# Generated by Django 2.2.1 on 2019-06-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stc001',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stc_id', models.CharField(max_length=45)),
                ('stc_name', models.CharField(max_length=45)),
                ('stc_dvsn', models.CharField(max_length=45)),
                ('now_price', models.BigIntegerField(default=0)),
                ('face_price', models.BigIntegerField(default=0)),
                ('tot_value', models.BigIntegerField(default=0)),
                ('pgm_id', models.CharField(max_length=10)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stc002',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_dt', models.CharField(max_length=45)),
                ('stc_id', models.CharField(max_length=45)),
                ('mod_cls_price', models.BigIntegerField(default=0)),
                ('cls_price', models.BigIntegerField(default=0)),
                ('diff_price', models.BigIntegerField(default=0)),
                ('strt_price', models.BigIntegerField(default=0)),
                ('high_price', models.BigIntegerField(default=0)),
                ('low_price', models.BigIntegerField(default=0)),
                ('deal_qnt', models.BigIntegerField(default=0)),
                ('pgm_id', models.CharField(max_length=10)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
