# Generated by Django 2.2.1 on 2019-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stc003',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_dt', models.CharField(max_length=45)),
                ('stc_id', models.CharField(max_length=45)),
                ('pbr', models.BigIntegerField(default=0)),
                ('per', models.BigIntegerField(default=0)),
                ('roe', models.BigIntegerField(default=0)),
                ('roa', models.BigIntegerField(default=0)),
                ('pgm_id', models.CharField(max_length=10)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
