# Generated by Django 2.2.1 on 2019-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_stc003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stc003',
            name='pbr',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stc003',
            name='per',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stc003',
            name='roa',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stc003',
            name='roe',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
