# Generated by Django 2.2.1 on 2019-05-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20190508_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='contents',
        ),
    ]
